#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
YouTube Cookies Management
Handles automatic cookie export from browsers for YouTube authentication.
"""

import os
import sys
import shutil
import tempfile
import sqlite3
from pathlib import Path
from typing import List, Tuple, Callable, Optional

from .constants import AUTH_COOKIES
from .utils import _dummy_log
from .cookie_normalizer import (
    create_isolated_cookie_snapshot,
    has_current_youtube_auth_cookies,
    is_valid_netscape_cookie_file,
    looks_like_youtube_auth_cookie_names,
    normalize_cookies_file,
)


# Флаг чтобы не пытаться много раз за сессию
_cookies_export_attempted = False

__all__ = [
    "auto_export_youtube_cookies",
    "create_isolated_cookie_snapshot",
    "default_youtube_cookies_path",
    "ensure_youtube_cookies",
    "has_current_youtube_auth_cookies",
    "is_valid_netscape_cookie_file",
    "normalize_cookies_file",
    "refresh_youtube_cookies",
    "_get_browser_paths",
    "_save_cookiejar_to_netscape",
    "_try_firefox_cookies",
]


def default_youtube_cookies_path() -> Path:
    """Return the writable youtube_cookies.txt path for source and frozen builds."""
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent / "youtube_cookies.txt"
    return Path(__file__).resolve().parents[2] / "youtube_cookies.txt"


def ensure_youtube_cookies(
    output_path: Optional[str] = None,
    log_callback: Optional[Callable] = None,
    auto_export: bool = True,
) -> Optional[str]:
    """Return a usable cookies file path, optionally exporting it from browsers."""
    log = log_callback or _dummy_log
    cookies_path = Path(output_path) if output_path else default_youtube_cookies_path()

    if cookies_path.exists():
        normalize_cookies_file(str(cookies_path), log)
        if (
            is_valid_netscape_cookie_file(str(cookies_path))
            and has_current_youtube_auth_cookies(str(cookies_path))
        ):
            return str(cookies_path)
        log("⚠️ Existing YouTube cookies are invalid or do not contain a login session")

    if not auto_export:
        return None

    if auto_export_youtube_cookies(str(cookies_path), log):
        normalize_cookies_file(str(cookies_path), log)
        if (
            is_valid_netscape_cookie_file(str(cookies_path))
            and has_current_youtube_auth_cookies(str(cookies_path))
        ):
            return str(cookies_path)

    return None


def _get_browser_paths() -> List[Tuple[str, Path]]:
    """Возвращает список (имя_браузера, путь_к_User_Data) для всех Chromium браузеров."""
    browsers = []
    
    if os.name == 'nt':
        local = Path(os.environ.get('LOCALAPPDATA', ''))
        appdata = Path(os.environ.get('APPDATA', ''))
        
        browser_paths = [
            ('Chrome', local / 'Google' / 'Chrome' / 'User Data'),
            ('Yandex', local / 'Yandex' / 'YandexBrowser' / 'User Data'),
            ('Edge', local / 'Microsoft' / 'Edge' / 'User Data'),
            ('Brave', local / 'BraveSoftware' / 'Brave-Browser' / 'User Data'),
            ('Opera', appdata / 'Opera Software' / 'Opera Stable'),
            ('Opera GX', appdata / 'Opera Software' / 'Opera GX Stable'),
            ('Vivaldi', local / 'Vivaldi' / 'User Data'),
            ('Chromium', local / 'Chromium' / 'User Data'),
        ]
    elif sys.platform == 'darwin':
        app_support = Path.home() / 'Library' / 'Application Support'
        browser_paths = [
            ('Chrome', app_support / 'Google' / 'Chrome'),
            ('Yandex', app_support / 'Yandex' / 'YandexBrowser'),
            ('Edge', app_support / 'Microsoft Edge'),
            ('Brave', app_support / 'BraveSoftware' / 'Brave-Browser'),
            ('Opera', app_support / 'com.operasoftware.Opera'),
            ('Vivaldi', app_support / 'Vivaldi'),
        ]
    else:
        config = Path.home() / '.config'
        browser_paths = [
            ('Chrome', config / 'google-chrome'),
            ('Yandex', config / 'yandex-browser'),
            ('Edge', config / 'microsoft-edge'),
            ('Brave', config / 'BraveSoftware' / 'Brave-Browser'),
            ('Opera', config / 'opera'),
            ('Vivaldi', config / 'vivaldi'),
            ('Chromium', config / 'chromium'),
        ]
    
    for name, path in browser_paths:
        if path.exists():
            browsers.append((name, path))
    
    return browsers


def _save_cookiejar_to_netscape(cookie_jar, output_path: str):
    """Сохраняет cookie jar в формате Netscape."""
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by ContentBot Pro\n\n")
        
        for cookie in cookie_jar:
            domain_initial_dot = str(cookie.domain.startswith('.')).upper()
            secure = str(cookie.secure).upper()
            expires = str(cookie.expires) if cookie.expires else "0"
            
            f.write(f"{cookie.domain}\t"
                    f"{domain_initial_dot}\t"
                    f"{cookie.path}\t"
                    f"{secure}\t"
                    f"{expires}\t"
                    f"{cookie.name}\t"
                    f"{cookie.value}\n")


def _try_firefox_cookies(output_path: str, log_callback: Callable, auth_cookies: List[str]) -> bool:
    """Пытается экспортировать cookies из Firefox."""
    if os.name == 'nt':
        firefox_dir = Path(os.environ.get('APPDATA', '')) / 'Mozilla' / 'Firefox' / 'Profiles'
    elif sys.platform == 'darwin':
        firefox_dir = Path.home() / 'Library' / 'Application Support' / 'Firefox' / 'Profiles'
    else:
        firefox_dir = Path.home() / '.mozilla' / 'firefox'
    
    if not firefox_dir.exists():
        return False
    
    profiles = list(firefox_dir.glob('*.default*'))
    profiles.extend(firefox_dir.glob('*.esr*'))
    
    for item in firefox_dir.iterdir():
        if item.is_dir() and (item / 'cookies.sqlite').exists():
            if item not in profiles:
                profiles.append(item)
    
    if not profiles:
        return False
    
    log_callback("🔍 Поиск профилей Firefox")
    
    for profile in profiles:
        cookies_db = profile / 'cookies.sqlite'
        if not cookies_db.exists():
            continue
        
        temp_fd, temp_db = tempfile.mkstemp(suffix='.sqlite', prefix='firefox_cookies_')
        os.close(temp_fd)
        
        try:
            shutil.copy2(cookies_db, temp_db)
        except Exception:
            temp_db = str(cookies_db)
        
        try:
            conn = sqlite3.connect(temp_db)
            cursor = conn.cursor()
            
            cursor.execute("""
                SELECT host, name, value, path, expiry, isSecure
                FROM moz_cookies 
                WHERE host LIKE '%youtube.com%' OR host LIKE '%google.com%'
            """)
            
            rows = cursor.fetchall()
            conn.close()
            
            if not rows:
                continue
            
            cookie_names = [row[1] for row in rows]
            requested_auth_cookies = set(auth_cookies or AUTH_COOKIES)
            is_logged_in = (
                looks_like_youtube_auth_cookie_names(cookie_names)
                or bool(requested_auth_cookies.intersection(cookie_names))
            )
            
            if is_logged_in:
                log_callback("✅ Найдены авторизованные cookies")
                
                with open(output_path, 'w', encoding='utf-8') as f:
                    f.write("# Netscape HTTP Cookie File\n")
                    f.write("# Generated from Firefox\n\n")
                    
                    for row in rows:
                        host, name, value, path, expiry, is_secure = row
                        domain_flag = "TRUE" if host.startswith('.') else "FALSE"
                        secure_flag = "TRUE" if is_secure else "FALSE"
                        expiry_str = str(expiry) if expiry else "0"
                        f.write(f"{host}\t{domain_flag}\t{path}\t{secure_flag}\t{expiry_str}\t{name}\t{value}\n")
                
                if temp_db != str(cookies_db) and os.path.exists(temp_db):
                    try:
                        os.unlink(temp_db)
                    except Exception:
                        pass
                
                return True
                
        except Exception:
            pass
        finally:
            if temp_db != str(cookies_db) and os.path.exists(temp_db):
                try:
                    os.unlink(temp_db)
                except Exception:
                    pass
    
    return False


def auto_export_youtube_cookies(
    output_path: str = "youtube_cookies.txt",
    log_callback: Optional[Callable] = None
) -> bool:
    """
    Автоматически находит и экспортирует cookies YouTube из ЛЮБОГО браузера.
    Поддерживает: Chrome, Yandex Browser, Edge, Brave, Opera, Vivaldi, Firefox, Chromium.
    """
    global _cookies_export_attempted
    
    if log_callback is None:
        log_callback = _dummy_log
    
    if _cookies_export_attempted:
        return has_current_youtube_auth_cookies(output_path)
    
    _cookies_export_attempted = True
    
    log_callback("🍪 Экспорт cookies из браузеров")
    
    try:
        import browser_cookie3
    except ImportError:
        log_callback("⚠️ browser_cookie3 не установлен")
        return False
    
    # 1. Firefox
    if _try_firefox_cookies(output_path, log_callback, AUTH_COOKIES):
        return has_current_youtube_auth_cookies(output_path)
    
    browsers = _get_browser_paths()
    
    if browsers:
        log_callback("🌐 Найдены браузеры для экспорта cookies")
    
    for browser_name, user_data_dir in browsers:
        browser_loader = {
            'Chrome': browser_cookie3.chrome,
            'Yandex': browser_cookie3.chromium,
            'Edge': browser_cookie3.edge,
            'Brave': browser_cookie3.brave,
            'Opera': browser_cookie3.opera,
            'Opera GX': browser_cookie3.opera,
            'Vivaldi': browser_cookie3.vivaldi,
            'Chromium': browser_cookie3.chromium,
        }.get(browser_name, browser_cookie3.chrome)
        profile_dirs = [user_data_dir / "Default"]
        profile_dirs.extend(user_data_dir.glob("Profile *"))
        
        valid_profiles = [p for p in profile_dirs if p.exists() and p.is_dir()]
        
        for profile in valid_profiles:
            
            cookie_file_paths = [
                profile / "Network" / "Cookies",
                profile / "Cookies"
            ]
            
            db_path = None
            for p in cookie_file_paths:
                if p.exists():
                    db_path = p
                    break
            
            if not db_path:
                continue

            temp_fd, temp_db = tempfile.mkstemp(suffix='.sqlite', prefix=f'cookies_{browser_name}_')
            os.close(temp_fd)
            
            try:
                shutil.copy2(db_path, temp_db)
            except Exception:
                temp_db = str(db_path)

            try:
                youtube_jar = browser_loader(
                    cookie_file=temp_db, domain_name='.youtube.com'
                )
                google_jar = browser_loader(
                    cookie_file=temp_db, domain_name='.google.com'
                )
                cookies_list = []
                seen_cookies = set()
                for cookie in list(youtube_jar) + list(google_jar):
                    key = (cookie.domain, cookie.path, cookie.name)
                    if key not in seen_cookies:
                        seen_cookies.add(key)
                        cookies_list.append(cookie)
                cookie_names = [c.name for c in cookies_list]
                is_logged_in = looks_like_youtube_auth_cookie_names(cookie_names)
                
                if len(cookies_list) > 0 and is_logged_in:
                    log_callback("✅ Cookies успешно экспортированы")
                    _save_cookiejar_to_netscape(cookies_list, output_path)
                    
                    if temp_db != str(db_path) and os.path.exists(temp_db):
                        try:
                            os.unlink(temp_db)
                        except Exception:
                            pass
                    
                    return has_current_youtube_auth_cookies(output_path)
                    
            except Exception:
                pass
            finally:
                if temp_db != str(db_path) and os.path.exists(temp_db):
                    try:
                        os.unlink(temp_db)
                    except Exception:
                        pass

    log_callback("❌ Не удалось экспортировать cookies из браузеров")
    log_callback("💡 Попробуйте войти в YouTube в браузере")
    log_callback("💡 Или используйте ручной экспорт cookies")
    return False


def refresh_youtube_cookies(
    output_path: str = "youtube_cookies.txt",
    log_callback: Optional[Callable] = None,
) -> bool:
    """Safely replace rejected cookies only when a fresh browser export differs."""
    global _cookies_export_attempted

    log = log_callback or _dummy_log
    def emit(message: str) -> None:
        try:
            log(message)
        except Exception:
            pass

    destination = Path(output_path)
    fd, temp_name = tempfile.mkstemp(
        prefix=".youtube_refresh_",
        suffix=".cookies.txt",
        dir=str(destination.parent or Path(".")),
    )
    os.close(fd)
    fresh_file = Path(temp_name)
    fresh_file.unlink(missing_ok=True)

    try:
        _cookies_export_attempted = False
        if not auto_export_youtube_cookies(str(fresh_file), log):
            return False
        if not normalize_cookies_file(str(fresh_file), log):
            return False
        if not has_current_youtube_auth_cookies(str(fresh_file)):
            emit("⚠️ Обновлённые cookies не содержат авторизацию YouTube")
            return False

        fresh_content = fresh_file.read_bytes()
        old_content = destination.read_bytes() if destination.exists() else b""
        if fresh_content == old_content:
            emit("⚠️ Браузер вернул те же cookies; повторная попытка не поможет")
            return False

        if destination.exists():
            backup = destination.with_suffix(".txt.rejected.backup")
            shutil.copy2(destination, backup)
        fresh_file.replace(destination)
        emit("✅ Cookies YouTube обновлены из браузера")
        return True
    except Exception as exc:
        emit(f"⚠️ Не удалось безопасно обновить cookies: {str(exc)[:100]}")
        return False
    finally:
        fresh_file.unlink(missing_ok=True)

